import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { OrderStatus, PaymentStatus, Prisma } from '@prisma/client';
import { randomUUID } from 'crypto';
import * as QRCode from 'qrcode';
import { PrismaService } from '../prisma/prisma.service';
import { CreateOrderDto, ManualPaymentDto, ShipOrderDto } from './orders.dto';
@Injectable() export class OrdersService {
 constructor(private prisma: PrismaService) {}
 list(user:any,status?:string){return this.prisma.order.findMany({where:{...(user.role==='SELLER'?{sellerId:user.id}:{}),...(status?{status:status as OrderStatus}:{})},include:{seller:{select:{id:true,name:true,email:true,companyName:true}},items:true,payments:true,files:true},orderBy:{createdAt:'desc'}})}
 async find(id:string,user:any){const o=await this.prisma.order.findUnique({where:{id},include:{seller:{select:{id:true,name:true,email:true,companyName:true}},items:true,reservations:true,payments:true,files:true,statusHistory:{orderBy:{createdAt:'asc'}}}});if(!o)throw new NotFoundException('Pedido não encontrado');if(user.role==='SELLER'&&o.sellerId!==user.id)throw new ForbiddenException('Pedido pertence a outro lojista');return o}
 async create(dto:CreateOrderDto,sellerId:string){const expiresAt=new Date(Date.now()+1800000),number=`FLX-${Date.now()}-${randomUUID().slice(0,6).toUpperCase()}`;return this.prisma.$transaction(async tx=>{const ids=[...new Set(dto.items.map(i=>i.productId))],products=await tx.product.findMany({where:{id:{in:ids},status:'ACTIVE',archivedAt:null}});if(products.length!==ids.length)throw new BadRequestException('Produto indisponível');let total=new Prisma.Decimal(0);const prepared=dto.items.map(i=>{const p=products.find(x=>x.id===i.productId)!;total=total.plus(p.price.mul(i.quantity));return{p,q:i.quantity}});for(const {p,q} of prepared){const c=await tx.product.updateMany({where:{id:p.id,stockOnHand:{gte:p.reservedStock+q}},data:{reservedStock:{increment:q},version:{increment:1}}});if(!c.count)throw new ConflictException(`Estoque insuficiente para ${p.sku}`)}const order=await tx.order.create({data:{number,sellerId,recipientName:dto.recipientName,recipientTaxId:dto.recipientTaxId,recipientAddress:dto.recipientAddress as Prisma.InputJsonValue,total,status:'AWAITING_PAYMENT',reservationExpiresAt:expiresAt,items:{create:prepared.map(({p,q})=>({productId:p.id,sku:p.sku,name:p.name,quantity:q,unitPrice:p.price}))},reservations:{create:prepared.map(({p,q})=>({productId:p.id,quantity:q,expiresAt}))},statusHistory:{create:{actorId:sellerId,toStatus:'AWAITING_PAYMENT',reason:'Pedido criado e estoque reservado'}}}});for(const {p,q} of prepared)await tx.stockMovement.create({data:{productId:p.id,orderId:order.id,actorId:sellerId,type:'RESERVATION',quantity:-q,balanceAfter:p.stockOnHand-p.reservedStock-q,reason:'Reserva por 30 minutos',reference:number}});const chargeId=randomUUID(),pix=`PIX-SIMULADO|${chargeId}|${total.toFixed(2)}|${number}`;const payment=await tx.payment.create({data:{orderId:order.id,provider:'SIMULATED',providerChargeId:chargeId,amount:total,pixCopyPaste:pix,qrCodeKey:chargeId,expiresAt}});return{...order,payment:{...payment,qrCodeDataUrl:await QRCode.toDataURL(pix)}}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
 async confirm(chargeId:string,amount:number){return this.prisma.$transaction(async tx=>{const p=await tx.payment.findUnique({where:{provider_providerChargeId:{provider:'SIMULATED',providerChargeId:chargeId}},include:{order:true}});if(!p)throw new NotFoundException('Cobrança não encontrada');if(p.status==='CONFIRMED')return p;const ok=p.amount.equals(amount),status:PaymentStatus=ok?'CONFIRMED':'REVIEW',next:OrderStatus=ok?'DOCUMENTS_PENDING':'PAYMENT_REVIEW';await tx.payment.update({where:{id:p.id},data:{status,confirmedAt:ok?new Date():undefined,reviewReason:ok?null:'Valor divergente'}});await tx.order.update({where:{id:p.orderId},data:{status:next}});await tx.orderStatusHistory.create({data:{orderId:p.orderId,actorId:p.order.sellerId,fromStatus:p.order.status,toStatus:next,reason:ok?'Pix confirmado pelo provedor':'Valor divergente'}});return{confirmed:ok,status}})}
 async review(id:string,dto:ManualPaymentDto,actorId:string){const p=await this.prisma.payment.findUnique({where:{id},include:{order:true}});if(!p)throw new NotFoundException('Pagamento não encontrado');return this.prisma.$transaction(async tx=>{const updated=await tx.payment.update({where:{id},data:{status:dto.status,reviewReason:dto.reason,confirmedAt:dto.status==='CONFIRMED'?new Date():null}});await tx.order.update({where:{id:p.orderId},data:{status:dto.status==='CONFIRMED'?'DOCUMENTS_PENDING':'PAYMENT_REVIEW'}});await tx.auditLog.create({data:{actorId,entityType:'payment',entityId:id,action:'manual_review',reason:dto.reason,before:{status:p.status},after:{status:dto.status}}});return updated})}
 async ship(id:string,dto:ShipOrderDto,actorId:string){return this.prisma.$transaction(async tx=>{const o=await tx.order.findUnique({where:{id},include:{reservations:{where:{status:'ACTIVE'}},files:true}});if(!o)throw new NotFoundException('Pedido não encontrado');if(!['DOCUMENTS_PENDING','PAID','SEPARATING','READY_TO_SHIP'].includes(o.status))throw new ConflictException('Pedido não está apto');if(!o.files.some(f=>f.kind==='SHIPPING_LABEL')||!o.files.some(f=>['INVOICE','CONTENT_DECLARATION'].includes(f.kind)))throw new ConflictException('Etiqueta e documento fiscal são obrigatórios');for(const r of o.reservations){const p=await tx.product.update({where:{id:r.productId},data:{stockOnHand:{decrement:r.quantity},reservedStock:{decrement:r.quantity},version:{increment:1}}});await tx.reservation.update({where:{id:r.id},data:{status:'CONSUMED'}});await tx.stockMovement.create({data:{productId:r.productId,orderId:id,actorId,type:'SHIPMENT',quantity:-r.quantity,balanceAfter:p.stockOnHand-p.reservedStock,reason:'Pedido expedido',reference:o.number}})}const updated=await tx.order.update({where:{id},data:{status:'SHIPPED',shippedAt:new Date(),trackingCode:dto.trackingCode,shippingNotes:dto.notes}});await tx.auditLog.create({data:{actorId,entityType:'order',entityId:id,action:'ship',reason:dto.notes}});return updated})}
}
